services:
  pg:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./init/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
