services:
  pg:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    volumes:
      - ./init/pg/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    build: fastApiApp
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
